services:
 frontend:
  container_name: frontend
  restart: unless-stopped
  build: /opt/cangular
  ports:
   - '80:80'
  volumes:
   - /opt/cangular/nginx.conf:/etc/nginx/conf.d/default.conf:ro
   - /var/log/frontend:/var/log/nginx
   - /opt/static:/var/www/html
  networks:
   - app-network
  command: ['nginx', '-g', 'daemon off;']

 backend:
  container_name: backend
  restart: unless-stopped
  build: ../backend
  ports:
   - '8090:8090'
  volumes:
   - /opt/data:/pb/pb_data
  networks:
   - app-network

networks:
 app-network:
