services:
 frontend:
  build:
   context: /opt/cangular
   dockerfile: Dockerfile
  networks:
   - app-network
  command: ['ng', 'build']

 backend:
  build: ../backend
  ports:
   - '8090:8090'
  volumes:
   - /opt/data:/pb/pb_data

 nginx:
  image: nginx:latest
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
   - /opt/static:/var/www/html/static
   - /opt/cangular/dist/:/var/www/html/front
  ports:
   - '80:80'
  depends_on:
   - frontend
   - backend
  networks:
   - app-network

networks:
 app-network:
  driver: bridge
