services:
 frontend:
  container_name: frontend
  build: /opt/cangular
  ports:
   - '80:80'
  volumes:
   - /opt/cangular:/app
   - /opt/cangular/node_modules
   - /opt/static:/var/www/html
   - /opt/cangular/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  networks:
   - app-network
  command: ['nginx', '-g', 'daemon off;']

 backend:
  container_name: backend
  build: ../backend
  ports:
   - '8090:8090'
  volumes:
   - /opt/data:/pb/pb_data
  networks:
   - app-network

networks:
 app-network:
