services:
 nginx:
  container_name: nginx
  image: nginx:alpine
  ports:
   - '80:80'
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
   - ../../../static:/usr/share/nginx/html/static

 frontend:
  container_name: frontend
  build: ../../
  ports:
   - '4200:4200'

 backend:
  container_name: backend
  build: ../backend
  ports:
   - '8090:8090'
  volumes:
   - ../../../data:/pb/pb_data
