name: Deploy
on:
 push:
  branches:
   - main
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Setup SSH
     uses: webfactory/ssh-agent@v0.9.0
     with:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
   - name: Run script
     run: ssh -o StrictHostKeyChecking=no auto@95.141.241.226 'bash -s < /opt/cangular/infra/scripts/deploy.sh'
